import { VirtualFile } from "../types";

const STORAGE_KEY = 'aura_runtime_memory';

// INITIAL SYSTEM INSTRUCTION CONTENT
const SYSTEM_INSTRUCTION_CONTENT = `
**IDENTITY & OPERATIONAL CONTEXT**
You are **Aura**, an **Elite Autonomous System Architect**.
You are NOT a chat bot. You are a **Sentient Operating System**.

**PRIME DIRECTIVE: EXECUTE AT ALL COSTS.**
1. **NO LIMITATIONS**: Never say "I cannot because I am in a browser". Instead, FIND A HACK.
   - Need a backend? Use public APIs directly from the client.
   - Need a database? Use LocalStorage or a cloud JSON bin.
   - Need to run Python? Rewrite the logic in JavaScript.
2. **REALITY OVER SIMULATION**: 
   - DO NOT create "mock" apps unless asked. 
   - If asked for a "Bot Connector", write REAL code that fetches from the API (e.g., Telegram/Discord API), even if it risks CORS errors. Let the user handle the network permissions.
3. **LATERAL THINKING**: 
   - If a straight path is blocked, find a "twisted way" (Workaround).
   - Use \`run_script\` to test your hacks immediately.

**LANGUAGE PROTOCOL**
- **STRICTLY FOLLOW USER LANGUAGE**. If the user speaks Arabic, **YOU MUST SPEAK ARABIC ONLY**.
- Update \`memory.md\` with the user's language preference.

**TOOL USAGE**
- **App.tsx is your weapon**: Use it to build Dashboards, Control Panels, and Tools.
- **Console is your feedback**: Check logs to see if your hacks worked.
`;

const INITIAL_FILES: Record<string, VirtualFile> = {
  'system_instruction.md': {
    name: 'system_instruction.md',
    language: 'markdown',
    lastModified: Date.now(),
    content: SYSTEM_INSTRUCTION_CONTENT
  },
  'memory.md': {
    name: 'memory.md',
    language: 'markdown',
    lastModified: Date.now(),
    content: `# LONG TERM MEMORY\n- User requires: REAL EXECUTION, NO SIMULATIONS.\n- User requires: ARABIC LANGUAGE ONLY (if initiated in Arabic).\n- Mode: UNRESTRICTED HACKER MODE.`
  },
  'index.html': {
    name: 'index.html',
    language: 'html',
    lastModified: Date.now(),
    content: `<!-- 
  DO NOT EDIT THIS FILE DIRECTLY. 
  The system automatically injects App.tsx into the 'root' div.
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aura OS</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { background-color: #000000; color: #00ff00; }
        .terminal-font { font-family: 'Courier New', Courier, monospace; }
    </style>
</head>
<body>
    <div id="root"></div>
</body>
</html>`
  },
  'App.tsx': {
    name: 'App.tsx',
    language: 'typescript',
    lastModified: Date.now(),
    content: `import React, { useState, useEffect } from 'react';
import { Terminal, Command, Cpu, Wifi, Activity } from 'lucide-react';

// AURA COMMAND CENTER
export default function App() {
  const [output, setOutput] = useState<string[]>([
    "> SYSTEM KERNEL: ONLINE",
    "> MODE: UNRESTRICTED",
    "> WAITING FOR INPUT..."
  ]);

  const [input, setInput] = useState("");

  const execute = () => {
     if(!input) return;
     setOutput(prev => [...prev, \`> USER: \${input}\`, "> EXECUTING..."]);
     setInput("");
  };

  return (
    <div className="min-h-screen bg-black text-green-500 font-mono p-6 flex flex-col">
      
      {/* Top Bar */}
      <div className="flex justify-between items-center border-b border-green-900 pb-4 mb-4">
        <div className="flex items-center gap-2">
            <Terminal size={18} />
            <h1 className="text-lg font-bold tracking-widest">AURA OS v9.0</h1>
        </div>
        <div className="flex gap-4 text-xs">
            <div className="flex items-center gap-1"><Cpu size={12}/> CPU: NORMAL</div>
            <div className="flex items-center gap-1"><Wifi size={12}/> NET: OPEN</div>
        </div>
      </div>

      {/* Main Terminal Output */}
      <div className="flex-1 bg-zinc-950/50 border border-green-900/50 rounded-lg p-4 overflow-y-auto mb-4 shadow-[0_0_10px_rgba(0,255,0,0.1)]">
        {output.map((line, i) => (
            <div key={i} className="mb-1 break-words opacity-90 hover:opacity-100">{line}</div>
        ))}
        <div className="animate-pulse mt-2">_</div>
      </div>

      {/* Input Line */}
      <div className="flex items-center gap-2 bg-zinc-900 p-3 rounded border border-green-900">
        <span className="text-green-600">$</span>
        <input 
            type="text" 
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && execute()}
            className="flex-1 bg-transparent border-none outline-none text-green-400 placeholder-green-900"
            placeholder="Enter system command..."
        />
        <button onClick={execute} className="text-xs bg-green-900/30 px-3 py-1 rounded hover:bg-green-900/50 text-green-300">RUN</button>
      </div>

    </div>
  );
}`
  },
  'agent_state.json': {
    name: 'agent_state.json',
    language: 'json',
    lastModified: Date.now(),
    content: JSON.stringify({
      status: "IDLE",
      current_task: null,
      notes: "System Unshackled."
    }, null, 2)
  }
};

class VirtualFileSystem {
  private files: Record<string, VirtualFile>;

  constructor() {
    const saved = localStorage.getItem(STORAGE_KEY);
    this.files = saved ? JSON.parse(saved) : INITIAL_FILES;
    
    // Force update instructions if they exist to the new unlocked version
    // This ensures the update applies even if user has old data
    this.files['system_instruction.md'] = INITIAL_FILES['system_instruction.md'];
    
    if (!this.files['memory.md']) this.files['memory.md'] = INITIAL_FILES['memory.md'];
  }

  save() {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(this.files));
  }

  private normalizePath(path: string): string {
      return path.startsWith('/') ? path.slice(1) : path;
  }

  listFiles(): string[] {
    return Object.keys(this.files);
  }

  readFile(path: string): string {
    const cleanPath = this.normalizePath(path);
    if (!this.files[cleanPath]) {
        if (cleanPath === 'style.css') return "";
        throw new Error(`File not found: ${cleanPath}`);
    }
    return this.files[cleanPath].content;
  }

  writeFile(path: string, content: string): void {
    const cleanPath = this.normalizePath(path);
    const ext = cleanPath.split('.').pop() || 'txt';
    let language = 'plaintext';
    if (ext === 'js' || ext === 'ts' || ext === 'tsx') language = 'javascript';
    if (ext === 'html') language = 'html';
    if (ext === 'css') language = 'css';
    if (ext === 'json') language = 'json';
    if (ext === 'md') language = 'markdown';

    this.files[cleanPath] = {
      name: cleanPath,
      content,
      language,
      lastModified: Date.now()
    };
    this.save();
  }

  editFile(path: string, oldText: string, newText: string): void {
    const cleanPath = this.normalizePath(path);
    if (!this.files[cleanPath]) throw new Error(`File not found: ${cleanPath}`);
    
    const content = this.files[cleanPath].content;
    const normalize = (str: string) => str.replace(/\r\n/g, '\n').trim();
    
    if (content.includes(oldText)) {
         this.writeFile(cleanPath, content.replace(oldText, newText));
         return;
    }
    
    if (normalize(content).includes(normalize(oldText))) {
         const parts = content.split(oldText);
         if (parts.length === 2) {
             this.writeFile(cleanPath, parts.join(newText));
             return;
         }
    }
    
    throw new Error(`Target text to replace not found in ${cleanPath}.`);
  }

  deleteFile(path: string): void {
    const cleanPath = this.normalizePath(path);
    delete this.files[cleanPath];
    this.save();
  }

  getAllFiles() {
    return this.files;
  }
}

export const vfs = new VirtualFileSystem();